### ISSUE TITLE
Make maybe from result type

### ISSUE THREAD

**Issue by s-m-i-t-a** [s-m-i-t-a/ex_maybe#2]
Example of use:

```elixir
123 = ExMaybe.from({:ok, 123})
nil = ExMaybe.from({:error, "error"})
```

**Comment by ondrej-tucek** [comment]
It's already done... see [from_result](https://github.com/s-m-i-t-a/ex_maybe/blob/90411d5ee6fd1cadd4a8da358344220ba0906e48/lib/ex_maybe.ex#L62) function.

**Comment by s-m-i-t-a** [comment]
> It's already done... see [from_result](https://github.com/s-m-i-t-a/ex_maybe/blob/90411d5ee6fd1cadd4a8da358344220ba0906e48/lib/ex_maybe.ex#L62) function.

Ok, then rename it, please.
